/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.action;

import java.io.UnsupportedEncodingException;
import java.lang.reflect.InvocationTargetException;
import java.net.URLEncoder;
import java.util.Date;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.mlw.vlh.ValueList;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.salmat.jbm.hibernate.HibernateSessionFactory;
import com.salmat.jbm.hibernate.SysLog;
import com.salmat.jbm.service.ValueListService;


/**
 * BaseAction for extends
 * 
 */
public abstract class BaseAction extends DispatchAction {
    /*
     * Generated Methods
     */
    private static ValueListService valueListService = ValueListService.getInstance();    
    
    /*
     * 新增初始化
     */
    public abstract ActionForward addInit(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * 編輯初始化
     */
    public abstract ActionForward editInit(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * edit submit
     */
    public abstract ActionForward editSubmit(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * add submit
     */
    public abstract ActionForward addSubmit(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * query result
     */
    public abstract ActionForward list(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * clone original form
     */
    public abstract ActionForward saveAsNewInit(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     * delete persist Object
     */
    public abstract ActionForward delete(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) ;
    
    /*
     *  1. set 查詢結果
     *  2. set 查詢的所有id
     *  3. set 返回的url
     */
    public void setGeneralAttribute(HttpServletRequest request, ValueList dataList, String pkName) throws IllegalAccessException, InvocationTargetException, NoSuchMethodException, UnsupportedEncodingException{
    	request.setAttribute("dataList", dataList);
        
    	String idList = "";
    	int i = 1;
    	for(Object obj : dataList.getList()){
        	idList += BeanUtils.getProperty(obj, pkName) + ",";        	
        }
        request.setAttribute("idList", idList);    
        String backToListURL = request.getRequestURI() +"?" + request.getQueryString();        
        request.setAttribute("backToListURL", URLEncoder.encode(backToListURL, "UTF-8"));
        
    	
    }
    //取得所需的查詢結果
    public synchronized ValueList getValueList(HttpServletRequest request, Map<String, String> param, String entryKey) {
        return valueListService.getValueList(request, entryKey, param);
    }
    
    public void saveSysLog(boolean isException, Exception e, String logType , String subject, String messageBody){
    	SysLog syslog = new SysLog();
    	syslog.setCreateDate(new Date());
    	syslog.setIsException(isException);
    	syslog.setLogType(logType);
    	if(e != null)
    		messageBody = e.getMessage() + "|" + messageBody;
    	syslog.setMessageBody(messageBody);
    	syslog.setSubject(subject );
    	HibernateSessionFactory.getSession().save(syslog);	
    }
    
}