/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.sf.json.JSONArray;

import org.apache.struts.action.ActionForm;

import com.salmat.jbm.hibernate.AcctChargeItem;
import com.salmat.jbm.hibernate.AcctItemFx;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.CustomerReceiver;
import com.salmat.jbm.hibernate.Employee;
import com.salmat.jbm.service.AcctChargeItemService;
import com.salmat.jbm.service.CodeService;
import com.salmat.jbm.service.CustomerReceiverService;
import com.salmat.jbm.service.CustomerService;
import com.salmat.jbm.service.EmployeeService;

public class AcctItemFxForm extends ActionForm {
	// Fields
	private Integer id;	
	private String name;
	private Double cost;	
	private Double acctPrice;
	private String printNo;
	
	private String custNo;
	private Boolean isMaterial;
	private String unitName;	
	private Integer unitCode;
	//計價標準id
	private Integer nonJbChargeItemId;	
	//單位
	private Integer categoryCode;
	private String categoryName;
	private String color;
	private Double pound;
	private Double length;
	private Double width;
	private Integer lengthUnit;
	private String lengthUnitNm;
	private Double weight;
	private Integer weightUnit;
	private String weightUnitNm;
	
	
	private String allCustomerReceivers;
	private List<Code> allCategories;
	private List<Employee> itEmps;
	private List<Customer> allCustomers;
	private List<Code> allUnits;
	private List<AcctChargeItem> nonJbChargeItems;
	private AcctItemFx acctItemFx;

	
	public AcctItemFx getAcctItemFx() {
		return acctItemFx;
	}

	public void setAcctItemFx(AcctItemFx acctItemFx) {
		this.acctItemFx = acctItemFx;
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getCost() {
		return cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Double getAcctPrice() {
		return acctPrice;
	}

	public void setAcctPrice(Double acctPrice) {
		this.acctPrice = acctPrice;
	}

	public String getPrintNo() {
		return printNo;
	}

	public void setPrintNo(String printNo) {
		this.printNo = printNo;
	}

	public String getCustNo() {
		return custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	public Boolean getIsMaterial() {
		return isMaterial;
	}

	public void setIsMaterial(Boolean isMaterial) {
		this.isMaterial = isMaterial;
	}
	
	public String getIsMaterialStr() {
		if(isMaterial == null)
			return "";
		else if(isMaterial)
		    return "1";
		else
			return "0";
	}

	public void setIsMaterialStr(String isMaterial) {
		if("1".equals(isMaterial))
			this.isMaterial = true;
		else if("0".equals(isMaterial))
			this.isMaterial = false;
		else
			this.isMaterial = null;
	}

	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public Integer getUnitCode() {
		return unitCode;
	}

	public void setUnitCode(Integer unitCode) {
		this.unitCode = unitCode;
	}
	
	public Integer getNonJbChargeItemId() {
		return nonJbChargeItemId;
	}

	public void setNonJbChargeItemId(Integer nonJbChargeItemId) {
		this.nonJbChargeItemId = nonJbChargeItemId;
	}



	public List<Employee> getItEmps() {
		if(itEmps == null){
		   
		   itEmps = EmployeeService.getInstance().getAllItEmp();
		}
		return itEmps; 		
	}

	public String getAllCustomerReceiversJson() {
		if (allCustomerReceivers == null) {
			List<CustomerReceiver> list = CustomerReceiverService.getInstance()
					.getAllCustomerReceivers();
			List<Map> returnList = new ArrayList<Map>();
			for (CustomerReceiver cr : list) {
				Map<String, String> map = new HashMap<String, String>();
				map.put("custNo", cr.getCustomer().getCustNo());
				map.put("receiverNo", cr.getReceiverNo());
				map.put("receiver", cr.getReceiver());
				returnList.add(map);
			}
			if (list != null)
				allCustomerReceivers = JSONArray.fromObject(returnList)
						.toString();
		}
		return allCustomerReceivers;

	}
	public List<Customer> getAllCustomers() {
		if (allCustomers == null) {
			List<Customer> list = CustomerService.getInstance().findAll();
								
			if (list != null)
				allCustomers = list;
		}
		return allCustomers;
	}
	
	public List<Code> getAllUnits() {
		if (allUnits == null) {
			List<Code> list = CodeService.getInstance().findByCodeTypeName("UNIT_NAME");
								
			if (list != null)
				allUnits = list;
		}
		return allUnits;
	}
	public List<Code> getAllCategories() {
		if (allCategories == null) {
			List<Code> list = CodeService.getInstance().findByCodeTypeName("MATERIAL_CATEGORY");
								
			if (list != null)
				allCategories = list;
		}
		return allCategories;
	}
	
	

	public List<AcctChargeItem> getNonJbChargeItems() {
		if (nonJbChargeItems == null) {
			List<AcctChargeItem> list = AcctChargeItemService.getInstance().findByProperty("itemType", "NON_JOB_BAG");								
			if (list != null)
				nonJbChargeItems = list;
		}
		return nonJbChargeItems;
	}

	public Integer getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(Integer categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Double getPound() {
		return pound;
	}

	public void setPound(Double pound) {
		this.pound = pound;
	}

	public Double getLength() {
		return length;
	}

	public void setLength(Double length) {
		this.length = length;
	}

	public Double getWidth() {
		return width;
	}

	public void setWidth(Double width) {
		this.width = width;
	}

	public Integer getLengthUnit() {
		return lengthUnit;
	}

	public void setLengthUnit(Integer lengthUnit) {
		this.lengthUnit = lengthUnit;
	}

	public String getLengthUnitNm() {
		return lengthUnitNm;
	}

	public void setLengthUnitNm(String lengthUnitNm) {
		this.lengthUnitNm = lengthUnitNm;
	}

	public Double getWeight() {
		return weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public Integer getWeightUnit() {
		return weightUnit;
	}

	public void setWeightUnit(Integer weightUnit) {
		this.weightUnit = weightUnit;
	}

	public String getWeightUnitNm() {
		return weightUnitNm;
	}

	public void setWeightUnitNm(String weightUnitNm) {
		this.weightUnitNm = weightUnitNm;
	}

}