/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class AmexForm extends ActionForm {
	private Integer id;
	private String country;
	private String afpName;
	private String jobCodeNo;
	private String typefile;
	private String speaker;
	private String special;
	private String macreport;
	private String mappingType;
	private String aebType;
	private Integer pages;	
	
	public String getAebType() {
		return aebType;
	}
	public void setAebType(String aebType) {
		this.aebType = aebType;
	}
	public Integer getPages() {
		return pages;
	}
	public void setPages(Integer pages) {
		this.pages = pages;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getAfpName() {
		return afpName;
	}
	public void setAfpName(String afpName) {
		this.afpName = afpName;
	}
	public String getJobCodeNo() {
		return jobCodeNo;
	}
	public void setJobCodeNo(String jobCodeNo) {
		this.jobCodeNo = jobCodeNo;
	}
	public String getTypefile() {
		return typefile;
	}
	public void setTypefile(String typefile) {
		this.typefile = typefile;
	}
	public String getSpeaker() {
		return speaker;
	}
	public void setSpeaker(String speaker) {
		this.speaker = speaker;
	}
	public String getSpecial() {
		return special;
	}
	public void setSpecial(String special) {
		this.special = special;
	}
	public String getMacreport() {
		return macreport;
	}
	public void setMacreport(String macreport) {
		this.macreport = macreport;
	}
	public String getMappingType() {
		return mappingType;
	}
	public void setMappingType(String mappingType) {
		this.mappingType = mappingType;
	}
	
	
}