/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class CodeForm extends ActionForm {
	private Integer id;
	private Integer ids[];
	private String codeTypeName;	
	private String codeTypeNames[];
	private String codeTypeNameTws[];
	private String codeKeys[];
	private String codeValueTws[];
	private String codeValueEns[];
	private String codeValueCns[];
	private Integer orderbyIds[];
	private Boolean isHiddens[];
	private String f1s[];
	private String f2s[];
	private String f3s[];	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer[] getIds() {
		return ids;
	}
	public void setIds(Integer[] ids) {
		this.ids = ids;
	}
	public String getCodeTypeName() {
		return codeTypeName;
	}
	public void setCodeTypeName(String codeTypeName) {
		this.codeTypeName = codeTypeName;
	}
	public String[] getCodeTypeNames() {
		return codeTypeNames;
	}
	public void setCodeTypeNames(String[] codeTypeNames) {
		this.codeTypeNames = codeTypeNames;
	}
	public String[] getCodeTypeNameTws() {
		return codeTypeNameTws;
	}
	public void setCodeTypeNameTws(String[] codeTypeNameTws) {
		this.codeTypeNameTws = codeTypeNameTws;
	}
	public String[] getCodeKeys() {
		return codeKeys;
	}
	public void setCodeKeys(String[] codeKeys) {
		this.codeKeys = codeKeys;
	}
	public String[] getCodeValueTws() {
		return codeValueTws;
	}
	public void setCodeValueTws(String[] codeValueTws) {
		this.codeValueTws = codeValueTws;
	}
	public String[] getCodeValueEns() {
		return codeValueEns;
	}
	public void setCodeValueEns(String[] codeValueEns) {
		this.codeValueEns = codeValueEns;
	}
	public String[] getCodeValueCns() {
		return codeValueCns;
	}
	public void setCodeValueCns(String[] codeValueCns) {
		this.codeValueCns = codeValueCns;
	}
	public Integer[] getOrderbyIds() {
		return orderbyIds;
	}
	public void setOrderbyIds(Integer[] orderbyIds) {
		this.orderbyIds = orderbyIds;
	}
	public Boolean[] getIsHiddens() {
		return isHiddens;
	}
	public void setIsHiddens(Boolean[] isHiddens) {
		this.isHiddens = isHiddens;
	}
	public String[] getF1s() {
		return f1s;
	}
	public void setF1s(String[] f1s) {
		this.f1s = f1s;
	}
	public String[] getF2s() {
		return f2s;
	}
	public void setF2s(String[] f2s) {
		this.f2s = f2s;
	}
	public String[] getF3s() {
		return f3s;
	}
	public void setF3s(String[] f3s) {
		this.f3s = f3s;
	}

	
}