/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;
import com.salmat.jbm.hibernate.JobBag;
import com.salmat.jbm.hibernate.JobCode;
import com.salmat.jbm.hibernate.Lcinfo;
import com.salmat.jbm.hibernate.Lginfo;
import com.salmat.jbm.hibernate.Lpinfo;
import com.salmat.jbm.hibernate.Mpinfo;
import com.salmat.jbm.hibernate.Psinfo;
import com.salmat.jbm.hibernate.Returninfo;



public class CompletedJobForm extends ActionForm {

	private String jobBagSpliteNo;
	private String jobBagNo;
	private Integer lpZipCodeBegin;
	private Integer lpZipCodeEnd;
	private Integer lpZipCodeDiff;	
	private Integer lpBlankBegin;
	private Integer lpBlankEnd;
	private Integer lpBlankDiff;	
	private Integer lpPaperBegin;
	private Integer lpPaperEnd;
	private Integer lpPaperDiff;

	private Integer lpPagesSeqBegin;
	private Integer lpPagesSeqEnd;
	private Integer lpPagesSeqDiff;
	private Integer lpPagesSeqExtra;
	
	
	private Integer lpAccountSeqBegin;
	private Integer lpAccountSeqEnd;
	private Integer lpAccountSeqDiff;	
	private String lpMachineName;
	private String lpCompletedUser;
	private String lpCompletedManager;
	private Boolean mpHasDamage;	
	private String mpCompletedUser;
	private String mpCompletedManager;
	private String mpMachineName;
	private String lgCompletedUser;
	private String lgCompletedManager;
	private Integer printingCount;
	private String afpFilename;

	
	// Fields
	private String empNo;
	private String empManagerNo;
	private String deptType;//回報單位 (L:LP/M:MP/I:LG)
	private Integer pagesHidden;
	private Integer sheetsHidden;
    private Integer accountsHidden;
    private String changeSubmit;

	

	public String getChangeSubmit() {
		return changeSubmit;
	}

	public void setChangeSubmit(String changeSubmit) {
		this.changeSubmit = changeSubmit;
	}

	public String getEmpNo() {
		return empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public String getEmpManagerNo() {
		return empManagerNo;
	}

	public void setEmpManagerNo(String empManagerNo) {
		this.empManagerNo = empManagerNo;
	}

	public String getJobBagSpliteNo() {
		return jobBagSpliteNo;
	}

	public void setJobBagSpliteNo(String jobBagSpliteNo) {
		this.jobBagSpliteNo = jobBagSpliteNo;
	}

	public String getJobBagNo() {
		return jobBagNo;
	}

	public void setJobBagNo(String jobBagNo) {
		this.jobBagNo = jobBagNo;
	}

	public Integer getLpZipCodeBegin() {
		return lpZipCodeBegin;
	}

	public void setLpZipCodeBegin(Integer lpZipCodeBegin) {
		this.lpZipCodeBegin = lpZipCodeBegin;
	}

	public Integer getLpZipCodeEnd() {
		return lpZipCodeEnd;
	}

	public void setLpZipCodeEnd(Integer lpZipCodeEnd) {
		this.lpZipCodeEnd = lpZipCodeEnd;
	}

	public Integer getLpBlankBegin() {
		return lpBlankBegin;
	}

	public void setLpBlankBegin(Integer lpBlankBegin) {
		this.lpBlankBegin = lpBlankBegin;
	}

	public Integer getLpBlankEnd() {
		return lpBlankEnd;
	}

	public void setLpBlankEnd(Integer lpBlankEnd) {
		this.lpBlankEnd = lpBlankEnd;
	}

	public Integer getLpPaperBegin() {
		return lpPaperBegin;
	}

	public void setLpPaperBegin(Integer lpPaperBegin) {
		this.lpPaperBegin = lpPaperBegin;
	}

	public Integer getLpPaperEnd() {
		return lpPaperEnd;
	}

	public void setLpPaperEnd(Integer lpPaperEnd) {
		this.lpPaperEnd = lpPaperEnd;
	}



	public Integer getLpPagesSeqBegin() {
		return lpPagesSeqBegin;
	}

	public void setLpPagesSeqBegin(Integer lpPagesSeqBegin) {
		this.lpPagesSeqBegin = lpPagesSeqBegin;
	}

	public Integer getLpPagesSeqEnd() {
		return lpPagesSeqEnd;
	}

	public void setLpPagesSeqEnd(Integer lpPagesSeqEnd) {
		this.lpPagesSeqEnd = lpPagesSeqEnd;
	}

	public Integer getLpPagesSeqDiff() {
		return lpPagesSeqDiff;
	}

	public void setLpPagesSeqDiff(Integer lpPagesSeqDiff) {
		this.lpPagesSeqDiff = lpPagesSeqDiff;
	}

	public Integer getLpPagesSeqExtra() {
		return lpPagesSeqExtra;
	}

	public void setLpPagesSeqExtra(Integer lpPagesSeqExtra) {
		this.lpPagesSeqExtra = lpPagesSeqExtra;
	}

	public Integer getLpAccountSeqBegin() {
		return lpAccountSeqBegin;
	}

	public void setLpAccountSeqBegin(Integer lpAccountSeqBegin) {
		this.lpAccountSeqBegin = lpAccountSeqBegin;
	}

	public Integer getLpAccountSeqEnd() {
		return lpAccountSeqEnd;
	}

	public void setLpAccountSeqEnd(Integer lpAccountSeqEnd) {
		this.lpAccountSeqEnd = lpAccountSeqEnd;
	}

	public String getLpMachineName() {
		return lpMachineName;
	}

	public void setLpMachineName(String lpMachineName) {
		this.lpMachineName = lpMachineName;
	}


	public Integer getPrintingCount() {
		return printingCount;
	}

	public void setPrintingCount(Integer printingCount) {
		this.printingCount = printingCount;
	}

	public String getAfpFilename() {
		return afpFilename;
	}

	public void setAfpFilename(String afpFilename) {
		this.afpFilename = afpFilename;
	}

	public String getDeptType() {
		return deptType;
	}

	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}

	public String getLpCompletedUser() {
		return lpCompletedUser;
	}

	public void setLpCompletedUser(String lpCompletedUser) {
		this.lpCompletedUser = lpCompletedUser;
	}

	public String getLpCompletedManager() {
		return lpCompletedManager;
	}

	public void setLpCompletedManager(String lpCompletedManager) {
		this.lpCompletedManager = lpCompletedManager;
	}

	public String getMpCompletedUser() {
		return mpCompletedUser;
	}

	public void setMpCompletedUser(String mpCompletedUser) {
		this.mpCompletedUser = mpCompletedUser;
	}

	public String getMpCompletedManager() {
		return mpCompletedManager;
	}

	public void setMpCompletedManager(String mpCompletedManager) {
		this.mpCompletedManager = mpCompletedManager;
	}

	public String getMpMachineName() {
		return mpMachineName;
	}

	public void setMpMachineName(String mpMachineName) {
		this.mpMachineName = mpMachineName;
	}

	public String getLgCompletedUser() {
		return lgCompletedUser;
	}

	public void setLgCompletedUser(String lgCompletedUser) {
		this.lgCompletedUser = lgCompletedUser;
	}

	public String getLgCompletedManager() {
		return lgCompletedManager;
	}

	public void setLgCompletedManager(String lgCompletedManager) {
		this.lgCompletedManager = lgCompletedManager;
	}

	public Integer getLpZipCodeDiff() {
		return lpZipCodeDiff;
	}

	public void setLpZipCodeDiff(Integer lpZipCodeDiff) {
		this.lpZipCodeDiff = lpZipCodeDiff;
	}

	public Integer getLpBlankDiff() {
		return lpBlankDiff;
	}

	public void setLpBlankDiff(Integer lpBlankDiff) {
		this.lpBlankDiff = lpBlankDiff;
	}

	public Integer getLpPaperDiff() {
		return lpPaperDiff;
	}

	public void setLpPaperDiff(Integer lpPaperDiff) {
		this.lpPaperDiff = lpPaperDiff;
	}



	public Integer getLpAccountSeqDiff() {
		return lpAccountSeqDiff;
	}

	public void setLpAccountSeqDiff(Integer lpAccountSeqDiff) {
		this.lpAccountSeqDiff = lpAccountSeqDiff;
	}

	public Boolean getMpHasDamage() {
		return mpHasDamage;
	}

	public void setMpHasDamage(Boolean mpHasDamage) {
		this.mpHasDamage = mpHasDamage;
	}


	public Integer getAccountsHidden() {
		return accountsHidden;
	}

	public void setAccountsHidden(Integer accountsHidden) {
		this.accountsHidden = accountsHidden;
	}

	public Integer getPagesHidden() {
		return pagesHidden;
	}

	public void setPagesHidden(Integer pagesHidden) {
		this.pagesHidden = pagesHidden;
	}

	public Integer getSheetsHidden() {
		return sheetsHidden;
	}

	public void setSheetsHidden(Integer sheetsHidden) {
		this.sheetsHidden = sheetsHidden;
	}

	

}