/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import net.sf.json.JSONArray;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.hibernate.AcctItem;
import com.salmat.jbm.hibernate.AcctItemFx;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.CustomerContract;
import com.salmat.jbm.hibernate.CustomerReceiver;
import com.salmat.jbm.hibernate.Employee;
import com.salmat.jbm.hibernate.HibernateSessionFactory;
import com.salmat.jbm.service.CustomerReceiverService;
import com.salmat.jbm.service.CustomerService;
import com.salmat.jbm.service.EmployeeService;

public class CustomerExtendsForm extends ActionForm {
	// Fields
	private String contractNo;
	private String custNo;
	private String receiverNo;
	private String accountManager;
	private String custService;
	private String backupStaff;
	private String contractName;
	private Integer deadlineCode;
	private Date contractBegin;
	private Date contractEnd;
	private Integer remindBeforeDeadline;
	private Integer idfBillingCycleCode;
	private String note;	
	private Integer freeHours;
	private Integer usedHours;
	private String[] itEmp;
	private String[] penalty;
	private String[] sla;
	private String[] operation;
	private String[] service;
	private FormFile file;	
	
	private Integer acctItemFxs1;
	private Integer acctItemFxs2;
	private Integer acctItemFxs3;
	private Integer acctItemFxs4;
	private Integer acctItemFxs5;
	private Integer acctItemFxs6;
	private Integer acctItemFxs7;
	private Integer acctItemFxs8;
	private Integer acctItemFxs9;
	private Integer acctItemFxs10;
	private Integer acctItemFxs11;
	private Integer acctItemFxs12;
	private Integer acctItemFxs13;
	private Integer acctItemFxs14;
	private Integer acctItemFxs15;
	private Integer acctItemFxs16;
	private Integer acctItemFxs17;
	private Integer acctItemFxs18;
	private Integer acctItemFxs19;
	private Integer acctItemFxs20;
	
	private Double toCustPrice1;
	private Double toCustPrice2;
	private Double toCustPrice3;
	private Double toCustPrice4;
	private Double toCustPrice5;
	private Double toCustPrice6;
	private Double toCustPrice7;
	private Double toCustPrice8;
	private Double toCustPrice9;
	private Double toCustPrice10;
	private Double toCustPrice11;
	private Double toCustPrice12;
	private Double toCustPrice13;
	private Double toCustPrice14;
	private Double toCustPrice15;
	private Double toCustPrice16;
	private Double toCustPrice17;
	private Double toCustPrice18;
	private Double toCustPrice19;
	private Double toCustPrice20;	
	private int acctItemSize;
	
	
	private CustomerContract customerContract;
	private String allCustomerReceivers;
	private List<CustomerReceiver> allReceivers;
	private List<Customer> allCustomers;
	private List<Employee> itEmps;
	private List<Employee> allCs;
	private List<Employee> allAccounts;
	private List<AcctItemFx> allAcctItemFxs;
	private List<AcctItemFx> custAcctItemFxs;
	private String allAcctItemFxsJson;
	
	
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getCustNo() {
		return custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	public String getReceiverNo() {
		return receiverNo;
	}

	public void setReceiverNo(String receiverNo) {
		this.receiverNo = receiverNo;
	}

	public String getAccountManager() {
		return accountManager;
	}

	public void setAccountManager(String accountManager) {
		this.accountManager = accountManager;
	}

	public String getCustService() {
		return custService;
	}

	public void setCustService(String custService) {
		this.custService = custService;
	}

	public String getBackupStaff() {
		return backupStaff;
	}

	public void setBackupStaff(String backupStaff) {
		this.backupStaff = backupStaff;
	}

	public String getContractName() {
		return contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	public Integer getDeadlineCode() {
		return deadlineCode;
	}

	public void setDeadlineCode(Integer deadlineCode) {
		this.deadlineCode = deadlineCode;
	}

	public Date getContractBegin() {
		return contractBegin;
	}

	public String[] getItEmp() {
		return itEmp;
	}

	public void setItEmp(String[] itEmp) {
		this.itEmp = itEmp;
	}

	public void setContractBegin(Date contractBegin) {
		this.contractBegin = contractBegin;
	}

	public Date getContractEnd() {
		return contractEnd;
	}

	public void setContractEnd(Date contractEnd) {
		this.contractEnd = contractEnd;
	}

	public Integer getRemindBeforeDeadline() {
		return remindBeforeDeadline;
	}

	public void setRemindBeforeDeadline(Integer remindBeforeDeadline) {
		this.remindBeforeDeadline = remindBeforeDeadline;
	}

	
	public Integer getIdfBillingCycleCode() {
		return idfBillingCycleCode;
	}

	public void setIdfBillingCycleCode(Integer idfBillingCycleCode) {
		this.idfBillingCycleCode = idfBillingCycleCode;
	}

	public String getNote() {
		return note;
	}

	public Integer getFreeHours() {
		return freeHours;
	}

	public void setFreeHours(Integer freeHours) {
		this.freeHours = freeHours;
	}

	public Integer getUsedHours() {
		return usedHours;
	}

	public void setUsedHours(Integer usedHours) {
		this.usedHours = usedHours;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public CustomerContract getCustomerContract() {
		return customerContract;
	}

	public void setCustomerContract(CustomerContract customerContract) {
		this.customerContract = customerContract;
		if(customerContract != null && customerContract.getAcctItems() != null){
			int i = 1;
			for(AcctItem acctItem : customerContract.getAcctItems()){
				try {
					BeanUtils.setProperty(this, "acctItemFxs" + i, acctItem.getAcctItemFx().getId());
					BeanUtils.setProperty(this, "toCustPrice" + i, acctItem.getToCustPrice());

				} catch (IllegalAccessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InvocationTargetException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}				
				i++;
			}
			this.acctItemSize = i;
			
		}
	}

	public String getAllCustomerReceivers() {
		return allCustomerReceivers;
	}

	public void setAllCustomerReceivers(String allCustomerReceivers) {
		this.allCustomerReceivers = allCustomerReceivers;
	}

	public void setAllReceivers(List<CustomerReceiver> allReceivers) {
		this.allReceivers = allReceivers;
	}

	public void setAllCustomers(List<Customer> allCustomers) {
		this.allCustomers = allCustomers;
	}

	public void setItEmps(List<Employee> itEmps) {
		this.itEmps = itEmps;
	}

	public Integer getAcctItemFxs1() {
		return acctItemFxs1;
	}

	public void setAcctItemFxs1(Integer acctItemFxs1) {
		this.acctItemFxs1 = acctItemFxs1;
	}

	public Integer getAcctItemFxs2() {
		return acctItemFxs2;
	}

	public void setAcctItemFxs2(Integer acctItemFxs2) {
		this.acctItemFxs2 = acctItemFxs2;
	}

	public Integer getAcctItemFxs3() {
		return acctItemFxs3;
	}

	public void setAcctItemFxs3(Integer acctItemFxs3) {
		this.acctItemFxs3 = acctItemFxs3;
	}

	public Integer getAcctItemFxs4() {
		return acctItemFxs4;
	}

	public void setAcctItemFxs4(Integer acctItemFxs4) {
		this.acctItemFxs4 = acctItemFxs4;
	}

	public Integer getAcctItemFxs5() {
		return acctItemFxs5;
	}

	public void setAcctItemFxs5(Integer acctItemFxs5) {
		this.acctItemFxs5 = acctItemFxs5;
	}

	public Integer getAcctItemFxs6() {
		return acctItemFxs6;
	}

	public void setAcctItemFxs6(Integer acctItemFxs6) {
		this.acctItemFxs6 = acctItemFxs6;
	}

	public Integer getAcctItemFxs7() {
		return acctItemFxs7;
	}

	public void setAcctItemFxs7(Integer acctItemFxs7) {
		this.acctItemFxs7 = acctItemFxs7;
	}

	public Integer getAcctItemFxs8() {
		return acctItemFxs8;
	}

	public void setAcctItemFxs8(Integer acctItemFxs8) {
		this.acctItemFxs8 = acctItemFxs8;
	}

	public Integer getAcctItemFxs9() {
		return acctItemFxs9;
	}

	public void setAcctItemFxs9(Integer acctItemFxs9) {
		this.acctItemFxs9 = acctItemFxs9;
	}

	public Integer getAcctItemFxs10() {
		return acctItemFxs10;
	}

	public void setAcctItemFxs10(Integer acctItemFxs10) {
		this.acctItemFxs10 = acctItemFxs10;
	}

	public Integer getAcctItemFxs11() {
		return acctItemFxs11;
	}

	public void setAcctItemFxs11(Integer acctItemFxs11) {
		this.acctItemFxs11 = acctItemFxs11;
	}

	public Integer getAcctItemFxs12() {
		return acctItemFxs12;
	}

	public void setAcctItemFxs12(Integer acctItemFxs12) {
		this.acctItemFxs12 = acctItemFxs12;
	}

	public Integer getAcctItemFxs13() {
		return acctItemFxs13;
	}

	public void setAcctItemFxs13(Integer acctItemFxs13) {
		this.acctItemFxs13 = acctItemFxs13;
	}

	public Integer getAcctItemFxs14() {
		return acctItemFxs14;
	}

	public void setAcctItemFxs14(Integer acctItemFxs14) {
		this.acctItemFxs14 = acctItemFxs14;
	}

	public Integer getAcctItemFxs15() {
		return acctItemFxs15;
	}

	public void setAcctItemFxs15(Integer acctItemFxs15) {
		this.acctItemFxs15 = acctItemFxs15;
	}

	public Integer getAcctItemFxs16() {
		return acctItemFxs16;
	}

	public void setAcctItemFxs16(Integer acctItemFxs16) {
		this.acctItemFxs16 = acctItemFxs16;
	}

	public Integer getAcctItemFxs17() {
		return acctItemFxs17;
	}

	public void setAcctItemFxs17(Integer acctItemFxs17) {
		this.acctItemFxs17 = acctItemFxs17;
	}

	public Integer getAcctItemFxs18() {
		return acctItemFxs18;
	}

	public void setAcctItemFxs18(Integer acctItemFxs18) {
		this.acctItemFxs18 = acctItemFxs18;
	}

	public Integer getAcctItemFxs19() {
		return acctItemFxs19;
	}

	public void setAcctItemFxs19(Integer acctItemFxs19) {
		this.acctItemFxs19 = acctItemFxs19;
	}

	public Integer getAcctItemFxs20() {
		return acctItemFxs20;
	}

	public void setAcctItemFxs20(Integer acctItemFxs20) {
		this.acctItemFxs20 = acctItemFxs20;
	}

	public Double getToCustPrice1() {
		return toCustPrice1;
	}

	public void setToCustPrice1(Double toCustPrice1) {
		this.toCustPrice1 = toCustPrice1;
	}

	public Double getToCustPrice2() {
		return toCustPrice2;
	}

	public void setToCustPrice2(Double toCustPrice2) {
		this.toCustPrice2 = toCustPrice2;
	}

	public Double getToCustPrice3() {
		return toCustPrice3;
	}

	public void setToCustPrice3(Double toCustPrice3) {
		this.toCustPrice3 = toCustPrice3;
	}

	public Double getToCustPrice4() {
		return toCustPrice4;
	}

	public void setToCustPrice4(Double toCustPrice4) {
		this.toCustPrice4 = toCustPrice4;
	}

	public Double getToCustPrice5() {
		return toCustPrice5;
	}

	public void setToCustPrice5(Double toCustPrice5) {
		this.toCustPrice5 = toCustPrice5;
	}

	public Double getToCustPrice6() {
		return toCustPrice6;
	}

	public void setToCustPrice6(Double toCustPrice6) {
		this.toCustPrice6 = toCustPrice6;
	}

	public Double getToCustPrice7() {
		return toCustPrice7;
	}

	public void setToCustPrice7(Double toCustPrice7) {
		this.toCustPrice7 = toCustPrice7;
	}

	public Double getToCustPrice8() {
		return toCustPrice8;
	}

	public void setToCustPrice8(Double toCustPrice8) {
		this.toCustPrice8 = toCustPrice8;
	}

	public Double getToCustPrice9() {
		return toCustPrice9;
	}

	public void setToCustPrice9(Double toCustPrice9) {
		this.toCustPrice9 = toCustPrice9;
	}

	public Double getToCustPrice10() {
		return toCustPrice10;
	}

	public void setToCustPrice10(Double toCustPrice10) {
		this.toCustPrice10 = toCustPrice10;
	}

	public Double getToCustPrice11() {
		return toCustPrice11;
	}

	public void setToCustPrice11(Double toCustPrice11) {
		this.toCustPrice11 = toCustPrice11;
	}

	public Double getToCustPrice12() {
		return toCustPrice12;
	}

	public void setToCustPrice12(Double toCustPrice12) {
		this.toCustPrice12 = toCustPrice12;
	}

	public Double getToCustPrice13() {
		return toCustPrice13;
	}

	public void setToCustPrice13(Double toCustPrice13) {
		this.toCustPrice13 = toCustPrice13;
	}

	public Double getToCustPrice14() {
		return toCustPrice14;
	}

	public void setToCustPrice14(Double toCustPrice14) {
		this.toCustPrice14 = toCustPrice14;
	}

	public Double getToCustPrice15() {
		return toCustPrice15;
	}

	public void setToCustPrice15(Double toCustPrice15) {
		this.toCustPrice15 = toCustPrice15;
	}

	public Double getToCustPrice16() {
		return toCustPrice16;
	}

	public void setToCustPrice16(Double toCustPrice16) {
		this.toCustPrice16 = toCustPrice16;
	}

	public Double getToCustPrice17() {
		return toCustPrice17;
	}

	public void setToCustPrice17(Double toCustPrice17) {
		this.toCustPrice17 = toCustPrice17;
	}

	public Double getToCustPrice18() {
		return toCustPrice18;
	}

	public void setToCustPrice18(Double toCustPrice18) {
		this.toCustPrice18 = toCustPrice18;
	}

	public Double getToCustPrice19() {
		return toCustPrice19;
	}

	public void setToCustPrice19(Double toCustPrice19) {
		this.toCustPrice19 = toCustPrice19;
	}

	public Double getToCustPrice20() {
		return toCustPrice20;
	}

	public void setToCustPrice20(Double toCustPrice20) {
		this.toCustPrice20 = toCustPrice20;
	}

	public List<Employee> getAllCs() {
		return allCs;
	}

	public void setAllCs(List<Employee> allCs) {
		this.allCs = allCs;
	}

	public void setAllAccounts(List<Employee> allAccounts) {
		this.allAccounts = allAccounts;
	}

	public void setAllAcctItemFxs(List<AcctItemFx> allAcctItemFxs) {
		this.allAcctItemFxs = allAcctItemFxs;
	}

	public void setCustAcctItemFxs(List<AcctItemFx> custAcctItemFxs) {
		this.custAcctItemFxs = custAcctItemFxs;
	}

	public void setAllAcctItemFxsJson(String allAcctItemFxsJson) {
		this.allAcctItemFxsJson = allAcctItemFxsJson;
	}

	public List<Employee> getItEmps() {
		if(itEmps == null){
		   
		   itEmps = EmployeeService.getInstance().getAllItEmp();
		}
		return itEmps; 		
	}
	public List<Employee> getAllCss() {
		if(allCs == null){		   
		   allCs = EmployeeService.getInstance().getAllCss();
		}
		return allCs; 		
	}
	public List<Employee> getAllAccounts() {
		if(allAccounts == null){		   
			allAccounts = EmployeeService.getInstance().getAllAccounts();
		}
		return allAccounts; 		
	}
	
	public List<CustomerReceiver> getAllReceivers() {
		getAllCustomerReceiversJson();
		return allReceivers;
	}

	public String getAllCustomerReceiversJson() {
		if (allReceivers == null) {
			List<CustomerReceiver> list = CustomerReceiverService.getInstance()
					.getAllCustomerReceivers();
			List<Map> returnList = new ArrayList<Map>();
			allReceivers = list;
			for (CustomerReceiver cr : list) {
				Map<String, String> map = new HashMap<String, String>();
				map.put("custNo", cr.getCustomer().getCustNo());
				map.put("receiverNo", cr.getReceiverNo());
				map.put("receiver", cr.getReceiver());
				returnList.add(map);
			}
			if (list != null)
				allCustomerReceivers = JSONArray.fromObject(returnList)
						.toString();
		}
		return allCustomerReceivers;
	}
	public List<Customer> getAllCustomers() {
		if (allCustomers == null) {
			List<Customer> list = CustomerService.getInstance().findAll();
								
			if (list != null)
				allCustomers = list;
		}
		return allCustomers;
	}

	public List<AcctItemFx> getAllAcctItemFxs() {
		if (allAcctItemFxs == null) {
			List<AcctItemFx> list = HibernateSessionFactory.getSession().createQuery("from AcctItemFx").list();								
			if (list != null){
				allAcctItemFxs = list;
				List<Map> returnList = new ArrayList<Map>();
				for(AcctItemFx ai : list){
					Map<String, String> map = new HashMap<String, String>();
					map.put("id", ai.getId() + "");
					map.put("custNo", ai.getCustNo());
					map.put("name", ai.getName());
					map.put("acctPrice", ai.getAcctPrice() + "");
					returnList.add(map);
				}
				allAcctItemFxsJson = JSONArray.fromObject(returnList).toString();
			}
		}
		return allAcctItemFxs;
	}
	public String getAllAcctItemFxsJson(){
		getAllAcctItemFxs();
		return allAcctItemFxsJson;
	}
	
	//取得此客戶相關的AcctItemFx，如果沒指定客戶時則是全部
	public List<AcctItemFx> getCustAcctItemFxs() {
		if (this.customerContract != null) {			
			List<AcctItemFx> list = HibernateSessionFactory.getSession().createQuery("from AcctItemFx where custNo = 'all' or custNo = '" + customerContract.getCustomer().getCustNo() + "'").list();								
			if (list != null){
				custAcctItemFxs = list;				
			}else{
				custAcctItemFxs = null;
				custAcctItemFxs = getAllAcctItemFxs();
			}
		}else{
			custAcctItemFxs = getAllAcctItemFxs();
		}
		return custAcctItemFxs;
	}

	public int getAcctItemSize() {
		return acctItemSize;
	}

	public void setAcctItemSize(int acctItemSize) {
		this.acctItemSize = acctItemSize;
	}

	public String[] getPenalty() {
		return penalty;
	}

	public void setPenalty(String[] penalty) {
		this.penalty = penalty;
	}

	public String[] getSla() {
		return sla;
	}

	public void setSla(String[] sla) {
		this.sla = sla;
	}

	public String[] getOperation() {
		return operation;
	}

	public void setOperation(String[] operation) {
		this.operation = operation;
	}

	public String[] getService() {
		return service;
	}

	public void setService(String[] service) {
		this.service = service;
	}

	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}
	
	@Override
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
   
        ActionErrors errors = new ActionErrors();
        if(getFile() != null){
           /*
           if( getFile().getFileSize()== 0){
               errors.add("fileError", new ActionMessage("error.file.required"));
               return errors;
           }           
           //only allow textfile to upload
           
           if(!"text/plain".equals(getFile().getContentType())){
               errors.add("fileError", new ActionMessage("error.file.type"));
               return errors;
           }
           */
           // file size cant larger than 50Mb
           if(getFile().getFileSize() > (1024000 * 50)){ 
               errors.add("fileError", new ActionMessage("error.file.size"));
                return errors; 
           }
        }
        return errors;
    }
}