/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class LCInfoForm extends ActionForm {
	private String lcNo;
	private Customer customer;
	private String progNm;
	private Boolean PList;
	private String nextEffectiveDate;
	private String nextProgNm;
	private Boolean nextPList;
	private String template;
	private String nextTemplate;	
	
    private String extraLgType1;
    private String extraLgType2;
    private String extraLgType3;
    private String extraLgType4;
    private String extraLgType5;
    private String extraLgType6;
    
    
	public String getExtraLgType1() {
		return extraLgType1;
	}


	public void setExtraLgType1(String extraLgType1) {
		this.extraLgType1 = extraLgType1;
	}


	public String getExtraLgType2() {
		return extraLgType2;
	}


	public void setExtraLgType2(String extraLgType2) {
		this.extraLgType2 = extraLgType2;
	}


	public String getExtraLgType3() {
		return extraLgType3;
	}


	public void setExtraLgType3(String extraLgType3) {
		this.extraLgType3 = extraLgType3;
	}


	public String getExtraLgType4() {
		return extraLgType4;
	}


	public void setExtraLgType4(String extraLgType4) {
		this.extraLgType4 = extraLgType4;
	}


	public String getExtraLgType5() {
		return extraLgType5;
	}


	public void setExtraLgType5(String extraLgType5) {
		this.extraLgType5 = extraLgType5;
	}


	public String getExtraLgType6() {
		return extraLgType6;
	}


	public void setExtraLgType6(String extraLgType6) {
		this.extraLgType6 = extraLgType6;
	}


	public String getTemplate() {
		return template;
	}


	public void setTemplate(String template) {
		this.template = template;
	}


	public String getNextTemplate() {
		return nextTemplate;
	}


	public void setNextTemplate(String nextTemplate) {
		this.nextTemplate = nextTemplate;
	}


	private String custNo;


	public String getLcNo() {
		return lcNo;
	}


	public void setLcNo(String lcNo) {
		this.lcNo = lcNo;
	}


	public Customer getCustomer() {
		return customer;
	}


	public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public String getProgNm() {
		return progNm;
	}


	public void setProgNm(String progNm) {
		this.progNm = progNm;
	}


	public Boolean getPList() {
		return PList;
	}


	public void setPList(Boolean pList) {
		PList = pList;
	}


	public String getNextEffectiveDate() {
		return nextEffectiveDate;
	}


	public void setNextEffectiveDate(String nextEffectiveDate) {
		this.nextEffectiveDate = nextEffectiveDate;
	}


	public String getNextProgNm() {
		return nextProgNm;
	}


	public void setNextProgNm(String nextProgNm) {
		this.nextProgNm = nextProgNm;
	}


	public Boolean getNextPList() {
		return nextPList;
	}


	public void setNextPList(Boolean nextPList) {
		this.nextPList = nextPList;
	}


	public String getCustNo() {
		return custNo;
	}


	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}



}