/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class LGFormForm extends ActionForm {
	private Integer id;
	private String custNo;
	private Integer codeMailToArea;
	private String mailToArea;
	private Integer codeLgType;
	private String lgType;
	private Integer qty;
	private Integer weight;
	private Integer postage;
	private String idfJobBagNo;
	private Integer statementNo;
	private Date dispatchDate;
	private String dispatcher;
	
	//Thor add修改交寄日期 2011/10/20
	private String lgYear;
	private String lgMonth;
	private String lgDate;

	
	
	//Edit Form
	
	private Integer ids[];
	private Integer delIds[];
	private Integer codeMailToAreas[];
	private String mailToAreas[];
	private Integer codeLgTypes[];
	private String lgTypes[];
	private Integer codeMailCategories[];
	private String mailCategories[];	
	private Integer qties[];
	private Integer weights[];
	private Double prices[];
	private String prognms[];	
	

	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustNo() {
		return custNo;
	}
	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}
	public Integer getCodeMailToArea() {
		return codeMailToArea;
	}
	public void setCodeMailToArea(Integer codeMailToArea) {
		this.codeMailToArea = codeMailToArea;
	}
	public String getMailToArea() {
		return mailToArea;
	}
	public void setMailToArea(String mailToArea) {
		this.mailToArea = mailToArea;
	}
	public Integer getCodeLgType() {
		return codeLgType;
	}
	public void setCodeLgType(Integer codeLgType) {
		this.codeLgType = codeLgType;
	}
	public String getLgType() {
		return lgType;
	}
	public void setLgType(String lgType) {
		this.lgType = lgType;
	}
	public Integer getQty() {
		return qty;
	}
	public void setQty(Integer qty) {
		this.qty = qty;
	}
	public Integer getWeight() {
		return weight;
	}
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	public Integer getPostage() {
		return postage;
	}
	public void setPostage(Integer postage) {
		this.postage = postage;
	}
	public String getIdfJobBagNo() {
		return idfJobBagNo;
	}
	public void setIdfJobBagNo(String idfJobBagNo) {
		this.idfJobBagNo = idfJobBagNo;
	}
	public Integer getStatementNo() {
		return statementNo;
	}
	public void setStatementNo(Integer statementNo) {
		this.statementNo = statementNo;
	}
	public Date getDispatchDate() {
		return dispatchDate;
	}
	public void setDispatchDate(Date dispatchDate) {
		this.dispatchDate = dispatchDate;
	}
	public String getDispatcher() {
		return dispatcher;
	}
	public void setDispatcher(String dispatcher) {
		this.dispatcher = dispatcher;
	}
	public Integer[] getIds() {
		return ids;
	}
	public void setIds(Integer[] ids) {
		this.ids = ids;
	}
	public Integer[] getDelIds() {
		return delIds;
	}
	public void setDelIds(Integer[] delIds) {
		this.delIds = delIds;
	}
	
	public Integer[] getCodeMailToAreas() {
		return codeMailToAreas;
	}
	public void setCodeMailToAreas(Integer[] codeMailToAreas) {
		this.codeMailToAreas = codeMailToAreas;
	}
	public String[] getMailToAreas() {
		return mailToAreas;
	}
	public void setMailToAreas(String[] mailToAreas) {
		this.mailToAreas = mailToAreas;
	}
	public Integer[] getCodeLgTypes() {
		return codeLgTypes;
	}
	public void setCodeLgTypes(Integer[] codeLgTypes) {
		this.codeLgTypes = codeLgTypes;
	}
	public String[] getLgTypes() {
		return lgTypes;
	}
	public void setLgTypes(String[] lgTypes) {
		this.lgTypes = lgTypes;
	}
	public Integer[] getQties() {
		return qties;
	}
	public void setQties(Integer[] qties) {
		this.qties = qties;
	}
	public Integer[] getWeights() {
		return weights;
	}
	public void setWeights(Integer[] weights) {
		this.weights = weights;
	}
	public Integer[] getCodeMailCategories() {
		return codeMailCategories;
	}
	public void setCodeMailCategories(Integer[] codeMailCategories) {
		this.codeMailCategories = codeMailCategories;
	}
	public String[] getMailCategories() {
		return mailCategories;
	}
	public void setMailCategories(String[] mailCategories) {
		this.mailCategories = mailCategories;
	}
	public Double[] getPrices() {
		return prices;
	}
	public void setPrices(Double[] prices) {
		this.prices = prices;
	}
	public String[] getPrognms() {
		return prognms;
	}
	public void setPrognms(String[] prognms) {
		this.prognms = prognms;
	}

	public String getLgYear() {
		return lgYear;
	}

	public void setLgYear(String lgYear) {
		this.lgYear = lgYear;
	}

	public String getLgMonth() {
		return lgMonth;
	}

	public void setLgMonth(String lgMonth) {
		this.lgMonth = lgMonth;
	}

	public String getLgDate() {
		return lgDate;
	}

	public void setLgDate(String lgDate) {
		this.lgDate = lgDate;
	}
	
	
	
}