/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class LPInfoForm extends ActionForm {
	// Fields

	private String lpNo;
	private Code codeByCodePrintType;
	private Code codeByCodePrinter;
	private Code codeByNextCodePrinter;
	private Code codeByNextCodePrintType;
	private Customer customer;
	private String printType;
	private String printSet;
	private double resolution;
	private double sugToner;
	private String remark;
	private double lpPrice;
	private String prodmemo;
	private Boolean printer;
	private String pcode1;
	private String pcode2;
	private String pcode3;
	private String pcode4;
	private String pcode5;
	private String pcode6;
	private String pcode7;
	private String pcode8;
	private String nextEffectiveDate;
	private String nextProdmemo;
	private String nextPcode1;
	private String nextPcode2;
	private String nextPcode3;
	private String nextPcode4;
	private String nextPcode5;
	private String nextPcode6;
	private String nextPcode7;
	private String nextPcode8;
	private String nextRemark;
	private String custNo;	
	private Integer codePrintType;
	private Integer codePrinter;	
	private Integer nextCodePrintType;
	private Integer nextCodePrinter;
	public String getLpNo() {
		return lpNo;
	}
	public void setLpNo(String lpNo) {
		this.lpNo = lpNo;
	}
	public Code getCodeByCodePrintType() {
		return codeByCodePrintType;
	}
	public void setCodeByCodePrintType(Code codeByCodePrintType) {
		this.codeByCodePrintType = codeByCodePrintType;
	}
	public Code getCodeByCodePrinter() {
		return codeByCodePrinter;
	}
	public void setCodeByCodePrinter(Code codeByCodePrinter) {
		this.codeByCodePrinter = codeByCodePrinter;
	}

	public Code getCodeByNextCodePrinter() {
		return codeByNextCodePrinter;
	}
	public void setCodeByNextCodePrinter(Code codeByNextCodePrinter) {
		this.codeByNextCodePrinter = codeByNextCodePrinter;
	}
	public Code getCodeByNextCodePrintType() {
		return codeByNextCodePrintType;
	}
	public void setCodeByNextCodePrintType(Code codeByNextCodePrintType) {
		this.codeByNextCodePrintType = codeByNextCodePrintType;
	}
	public Customer getCustomer() {
		return customer;
	}
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public String getPrintType() {
		return printType;
	}
	public void setPrintType(String printType) {
		this.printType = printType;
	}
	public String getPrintSet() {
		return printSet;
	}
	public void setPrintSet(String printSet) {
		this.printSet = printSet;
	}
	public double getResolution() {
		return resolution;
	}
	public void setResolution(double resolution) {
		this.resolution = resolution;
	}
	public double getSugToner() {
		return sugToner;
	}
	public void setSugToner(double sugToner) {
		this.sugToner = sugToner;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public double getLpPrice() {
		return lpPrice;
	}
	public void setLpPrice(double lpPrice) {
		this.lpPrice = lpPrice;
	}
	public String getProdmemo() {
		return prodmemo;
	}
	public void setProdmemo(String prodmemo) {
		this.prodmemo = prodmemo;
	}
	public Boolean isPrinter() {
		return printer;
	}
	public void setPrinter(Boolean printer) {
		this.printer = printer;
	}
	public String getPcode1() {
		return pcode1;
	}
	public void setPcode1(String pcode1) {
		this.pcode1 = pcode1;
	}
	public String getPcode2() {
		return pcode2;
	}
	public void setPcode2(String pcode2) {
		this.pcode2 = pcode2;
	}
	public String getPcode3() {
		return pcode3;
	}
	public void setPcode3(String pcode3) {
		this.pcode3 = pcode3;
	}
	public String getPcode4() {
		return pcode4;
	}
	public void setPcode4(String pcode4) {
		this.pcode4 = pcode4;
	}
	public String getNextEffectiveDate() {
		return nextEffectiveDate;
	}
	public void setNextEffectiveDate(String nextEffectiveDate) {
		this.nextEffectiveDate = nextEffectiveDate;
	}
	public String getNextProdmemo() {
		return nextProdmemo;
	}
	public void setNextProdmemo(String nextProdmemo) {
		this.nextProdmemo = nextProdmemo;
	}
	public String getNextPcode1() {
		return nextPcode1;
	}
	public void setNextPcode1(String nextPcode1) {
		this.nextPcode1 = nextPcode1;
	}
	public String getNextPcode2() {
		return nextPcode2;
	}
	public void setNextPcode2(String nextPcode2) {
		this.nextPcode2 = nextPcode2;
	}
	public String getNextPcode3() {
		return nextPcode3;
	}
	public void setNextPcode3(String nextPcode3) {
		this.nextPcode3 = nextPcode3;
	}
	public String getNextPcode4() {
		return nextPcode4;
	}
	public void setNextPcode4(String nextPcode4) {
		this.nextPcode4 = nextPcode4;
	}
	public String getNextRemark() {
		return nextRemark;
	}
	public void setNextRemark(String nextRemark) {
		this.nextRemark = nextRemark;
	}
	public String getCustNo() {
		return custNo;
	}
	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}
	public Integer getCodePrintType() {
		return codePrintType;
	}
	public void setCodePrintType(Integer codePrintType) {
		this.codePrintType = codePrintType;
	}
	public Integer getCodePrinter() {
		return codePrinter;
	}
	public void setCodePrinter(Integer codePrinter) {
		this.codePrinter = codePrinter;
	}
	public Integer getNextCodePrintType() {
		return nextCodePrintType;
	}
	public void setNextCodePrintType(Integer nextCodePrintType) {
		this.nextCodePrintType = nextCodePrintType;
	}
	public Integer getNextCodePrinter() {
		return nextCodePrinter;
	}
	public void setNextCodePrinter(Integer nextCodePrinter) {
		this.nextCodePrinter = nextCodePrinter;
	}
	public String getPcode5() {
		return pcode5;
	}
	public void setPcode5(String pcode5) {
		this.pcode5 = pcode5;
	}
	public String getPcode6() {
		return pcode6;
	}
	public void setPcode6(String pcode6) {
		this.pcode6 = pcode6;
	}
	public String getPcode7() {
		return pcode7;
	}
	public void setPcode7(String pcode7) {
		this.pcode7 = pcode7;
	}
	public String getPcode8() {
		return pcode8;
	}
	public void setPcode8(String pcode8) {
		this.pcode8 = pcode8;
	}
	public String getNextPcode5() {
		return nextPcode5;
	}
	public void setNextPcode5(String nextPcode5) {
		this.nextPcode5 = nextPcode5;
	}
	public String getNextPcode6() {
		return nextPcode6;
	}
	public void setNextPcode6(String nextPcode6) {
		this.nextPcode6 = nextPcode6;
	}
	public String getNextPcode7() {
		return nextPcode7;
	}
	public void setNextPcode7(String nextPcode7) {
		this.nextPcode7 = nextPcode7;
	}
	public String getNextPcode8() {
		return nextPcode8;
	}
	public void setNextPcode8(String nextPcode8) {
		this.nextPcode8 = nextPcode8;
	}
	public Boolean getPrinter() {
		return printer;
	}	
	
}