/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class MPInfoForm extends ActionForm {
	// Fields

	private String mpNo;
	private Customer customer;
	private String size;
	private String stampSet;
	private Boolean stampSetFg;
	private Boolean selectFg;
	private Boolean zipFg;
	private String remark;
	private double mpPrice;
	private String printCode;
	private double insertCnt;
	private String mp1Word;
	private String mp2Word;
	private String mp3Word;
	private String mp4Word;
	private String prodmemo;
	private Boolean mp1Iflag;
	private Boolean mp2Iflag;
	private Boolean mp3Iflag;
	private Boolean mp4Iflag;
	private String printCodeImage;
	private String mp1Image;
	private String mp2Image;
	private String mp3Image;
	private String mp4Image;
	private String nextEffectiveDate;
	private String nextProdmemo;
	private String nextPrintCode;
	private String nextPrintCodeImage;
	private Boolean nextStampSetFg;
	private Boolean nextZipFg;
	private Boolean nextSelectFg;
	private String nextRemark;
	private String nextMp1Word;
	private String nextMp2Word;
	private String nextMp3Word;
	private String nextMp4Word;
	private Boolean nextMp1Iflag;
	private Boolean nextMp2Iflag;
	private Boolean nextMp3Iflag;
	private Boolean nextMp4Iflag;
	private String nextMp1Image;
	private String nextMp2Image;
	private String nextMp3Image;
	private String nextMp4Image;
	
	
	private String custNo;


	public String getMpNo() {
		return mpNo;
	}


	public void setMpNo(String mpNo) {
		this.mpNo = mpNo;
	}


	public Customer getCustomer() {
		return customer;
	}


	public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public String getSize() {
		return size;
	}


	public void setSize(String size) {
		this.size = size;
	}


	public String getStampSet() {
		return stampSet;
	}


	public void setStampSet(String stampSet) {
		this.stampSet = stampSet;
	}


	public Boolean getStampSetFg() {
		return stampSetFg;
	}


	public void setStampSetFg(Boolean stampSetFg) {
		this.stampSetFg = stampSetFg;
	}


	public Boolean getSelectFg() {
		return selectFg;
	}


	public void setSelectFg(Boolean selectFg) {
		this.selectFg = selectFg;
	}


	public Boolean getZipFg() {
		return zipFg;
	}


	public void setZipFg(Boolean zipFg) {
		this.zipFg = zipFg;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public double getMpPrice() {
		return mpPrice;
	}


	public void setMpPrice(double mpPrice) {
		this.mpPrice = mpPrice;
	}


	public String getPrintCode() {
		return printCode;
	}


	public void setPrintCode(String printCode) {
		this.printCode = printCode;
	}


	public double getInsertCnt() {
		return insertCnt;
	}


	public void setInsertCnt(double insertCnt) {
		this.insertCnt = insertCnt;
	}



	public String getMp1Word() {
		return mp1Word;
	}


	public void setMp1Word(String mp1Word) {
		this.mp1Word = mp1Word;
	}


	public String getMp2Word() {
		return mp2Word;
	}


	public void setMp2Word(String mp2Word) {
		this.mp2Word = mp2Word;
	}


	public String getMp3Word() {
		return mp3Word;
	}


	public void setMp3Word(String mp3Word) {
		this.mp3Word = mp3Word;
	}


	public String getMp4Word() {
		return mp4Word;
	}


	public void setMp4Word(String mp4Word) {
		this.mp4Word = mp4Word;
	}


	public String getProdmemo() {
		return prodmemo;
	}


	public void setProdmemo(String prodmemo) {
		this.prodmemo = prodmemo;
	}


	public Boolean getMp1Iflag() {
		return mp1Iflag;
	}


	public void setMp1Iflag(Boolean mp1Iflag) {
		this.mp1Iflag = mp1Iflag;
	}


	public Boolean getMp2Iflag() {
		return mp2Iflag;
	}


	public void setMp2Iflag(Boolean mp2Iflag) {
		this.mp2Iflag = mp2Iflag;
	}


	public Boolean getMp3Iflag() {
		return mp3Iflag;
	}


	public void setMp3Iflag(Boolean mp3Iflag) {
		this.mp3Iflag = mp3Iflag;
	}


	public Boolean getMp4Iflag() {
		return mp4Iflag;
	}


	public void setMp4Iflag(Boolean mp4Iflag) {
		this.mp4Iflag = mp4Iflag;
	}


	public String getPrintCodeImage() {
		return printCodeImage;
	}


	public void setPrintCodeImage(String printCodeImage) {
		this.printCodeImage = printCodeImage;
	}


	public String getMp1Image() {
		return mp1Image;
	}


	public void setMp1Image(String mp1Image) {
		this.mp1Image = mp1Image;
	}


	public String getMp2Image() {
		return mp2Image;
	}


	public void setMp2Image(String mp2Image) {
		this.mp2Image = mp2Image;
	}


	public String getMp3Image() {
		return mp3Image;
	}


	public void setMp3Image(String mp3Image) {
		this.mp3Image = mp3Image;
	}


	public String getMp4Image() {
		return mp4Image;
	}


	public void setMp4Image(String mp4Image) {
		this.mp4Image = mp4Image;
	}


	public String getNextEffectiveDate() {
		return nextEffectiveDate;
	}


	public void setNextEffectiveDate(String nextEffectiveDate) {
		this.nextEffectiveDate = nextEffectiveDate;
	}


	public String getNextProdmemo() {
		return nextProdmemo;
	}


	public void setNextProdmemo(String nextProdmemo) {
		this.nextProdmemo = nextProdmemo;
	}


	public String getNextPrintCode() {
		return nextPrintCode;
	}


	public void setNextPrintCode(String nextPrintCode) {
		this.nextPrintCode = nextPrintCode;
	}


	public String getNextPrintCodeImage() {
		return nextPrintCodeImage;
	}


	public void setNextPrintCodeImage(String nextPrintCodeImage) {
		this.nextPrintCodeImage = nextPrintCodeImage;
	}


	public Boolean getNextStampSetFg() {
		return nextStampSetFg;
	}


	public void setNextStampSetFg(Boolean nextStampSetFg) {
		this.nextStampSetFg = nextStampSetFg;
	}


	public Boolean getNextZipFg() {
		return nextZipFg;
	}


	public void setNextZipFg(Boolean nextZipFg) {
		this.nextZipFg = nextZipFg;
	}


	public Boolean getNextSelectFg() {
		return nextSelectFg;
	}


	public void setNextSelectFg(Boolean nextSelectFg) {
		this.nextSelectFg = nextSelectFg;
	}


	public String getNextRemark() {
		return nextRemark;
	}


	public void setNextRemark(String nextRemark) {
		this.nextRemark = nextRemark;
	}




	public String getNextMp1Word() {
		return nextMp1Word;
	}


	public void setNextMp1Word(String nextMp1Word) {
		this.nextMp1Word = nextMp1Word;
	}


	public String getNextMp2Word() {
		return nextMp2Word;
	}


	public void setNextMp2Word(String nextMp2Word) {
		this.nextMp2Word = nextMp2Word;
	}


	public String getNextMp3Word() {
		return nextMp3Word;
	}


	public void setNextMp3Word(String nextMp3Word) {
		this.nextMp3Word = nextMp3Word;
	}


	public String getNextMp4Word() {
		return nextMp4Word;
	}


	public void setNextMp4Word(String nextMp4Word) {
		this.nextMp4Word = nextMp4Word;
	}


	public Boolean getNextMp1Iflag() {
		return nextMp1Iflag;
	}


	public void setNextMp1Iflag(Boolean nextMp1Iflag) {
		this.nextMp1Iflag = nextMp1Iflag;
	}


	public Boolean getNextMp2Iflag() {
		return nextMp2Iflag;
	}


	public void setNextMp2Iflag(Boolean nextMp2Iflag) {
		this.nextMp2Iflag = nextMp2Iflag;
	}


	public Boolean getNextMp3Iflag() {
		return nextMp3Iflag;
	}


	public void setNextMp3Iflag(Boolean nextMp3Iflag) {
		this.nextMp3Iflag = nextMp3Iflag;
	}


	public Boolean getNextMp4Iflag() {
		return nextMp4Iflag;
	}


	public void setNextMp4Iflag(Boolean nextMp4Iflag) {
		this.nextMp4Iflag = nextMp4Iflag;
	}


	public String getNextMp1Image() {
		return nextMp1Image;
	}


	public void setNextMp1Image(String nextMp1Image) {
		this.nextMp1Image = nextMp1Image;
	}


	public String getNextMp2Image() {
		return nextMp2Image;
	}


	public void setNextMp2Image(String nextMp2Image) {
		this.nextMp2Image = nextMp2Image;
	}


	public String getNextMp3Image() {
		return nextMp3Image;
	}


	public void setNextMp3Image(String nextMp3Image) {
		this.nextMp3Image = nextMp3Image;
	}


	public String getNextMp4Image() {
		return nextMp4Image;
	}


	public void setNextMp4Image(String nextMp4Image) {
		this.nextMp4Image = nextMp4Image;
	}


	public String getCustNo() {
		return custNo;
	}


	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	
}