/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.salmat.jbm.struts.form;

import java.sql.Clob;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.salmat.jbm.bean.*;
import com.salmat.jbm.hibernate.Code;
import com.salmat.jbm.hibernate.Customer;
import com.salmat.jbm.hibernate.Employee;



public class SyslogForm extends ActionForm {
	private Integer id;
	private String logType;
	private String subject;
	private String messageBody;
	private Integer isException;
	private String errorLog;
	private String createDate;
	private String logDateBegin;
	private String logDateEnd;	
	private Integer pageSize;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getLogType() {
		return logType;
	}
	public void setLogType(String logType) {
		this.logType = logType;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getMessageBody() {
		return messageBody;
	}
	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody;
	}

	public Integer getIsException() {
		return isException;
	}
	public void setIsException(Integer isException) {
		this.isException = isException;
	}
	public String getErrorLog() {
		return errorLog;
	}
	public void setErrorLog(String errorLog) {
		this.errorLog = errorLog;
	}
	public String getCreateDate() {
		return createDate;
	}
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}
	public String getLogDateBegin() {
		return logDateBegin;
	}
	public void setLogDateBegin(String logDateBegin) {
		this.logDateBegin = logDateBegin;
	}
	public String getLogDateEnd() {
		return logDateEnd;
	}
	public void setLogDateEnd(String logDateEnd) {
		this.logDateEnd = logDateEnd;
	}
	public Integer getPageSize() {
		return pageSize;
	}
	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
	
    public void reset(ActionMapping mapping,
            HttpServletRequest request) {
    	this.id=null;
    	this.logType=null;
    	this.subject=null;
    	this.messageBody=null;
    	this.isException=null;
    	this.errorLog=null;
    	this.createDate=null;
    	this.logDateBegin=null;
    	this.logDateEnd=null;	
    	this.pageSize=null;
    } 
	
	
}